### ISSUE TITLE
Network Config Override

### ISSUE THREAD

**Issue by Siwuxie-x** [isHarryh/Ark-Studio#1]
Hello, 
I am a beginner and interested in the project. And I was tring to figure out how this app work. But I noticed that here in the backend/ArkClinet.py line 35. As we want a override-true should it be `if config.get('override', Ture):`? 

https://github.com/isHarryh/Ark-Studio/blob/db16a79ecc5bafa50ef673161ca2ca0e2228157b/src/backend/ArkClient.py#L33-L37

**Comment by isHarryh** [comment]
The `config.get` is a method of dict type that gets a value by a given key.

The 1st argument 'override' is the **key** of the value we want to get. The 2nd argument `False` is the **default value** to return in case the key is not existed.

```
if config.get('override', False):
```

Sorry that this project is still not completed.

**Comment by Siwuxie-x** [comment]
Thanks for your explanation. It is me that had the wrong understanding.
